version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=$GIN_MODE
      - APP_PORT=$APP_PORT
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
      - YOUTUBE_API_KEY_1=$YOUTUBE_API_KEY_1
      - YOUTUBE_API_KEY_2=$YOUTUBE_API_KEY_2
      - YOUTUBE_API_KEY_3=$YOUTUBE_API_KEY_3
      - YOUTUBE_SEARCH_QUERY=$YOUTUBE_SEARCH_QUERY
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3366:3306
    environment:
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: